/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package universidadejemplo.Vistas;

import java.awt.Color;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author USURIO
 */
public class PantallaInicio extends javax.swing.JFrame {

    private int auxiliar = 0;
    private boolean realizado = false;
    hilo ejecutar = new hilo();

    /**
     * Creates new form NewJFrame
     */
    public PantallaInicio() {
        setUndecorated(true);
        initComponents();
        //Para que no se vea nada
        PantallaInicio.this.getRootPane().setOpaque(false);
        //Para darle color
        PantallaInicio.this.getContentPane().setBackground(new Color(0, 0, 0, 0));
        PantallaInicio.this.setBackground(new Color(0, 0, 0, 0));
        this.setResizable(false);
        this.setLocationRelativeTo(this);

    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelRound1 = new universidadejemplo.Vistas.PanelRound();
        barra = new javax.swing.JProgressBar();
        text = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        text1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setAlwaysOnTop(true);
        setCursor(new java.awt.Cursor(java.awt.Cursor.WAIT_CURSOR));
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelRound1.setBackground(new java.awt.Color(41, 40, 65));
        panelRound1.setRoundBottomLeft(50);
        panelRound1.setRoundBottomRight(50);
        panelRound1.setRoundTopLeft(50);
        panelRound1.setRoundTopRight(50);
        panelRound1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        barra.setBackground(new java.awt.Color(28, 27, 41));
        barra.setFont(new java.awt.Font("Bell MT", 0, 3)); // NOI18N
        barra.setForeground(new java.awt.Color(88, 101, 242));
        panelRound1.add(barra, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, 510, 6));

        text.setForeground(new java.awt.Color(255, 184, 105));
        text.setText("v 1.2.1 2023");
        panelRound1.add(text, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, 220, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Recurso 9.png"))); // NOI18N
        panelRound1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, -1));

        jLabel2.setFont(new java.awt.Font("Open Sans Medium", 0, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 184, 105));
        jLabel2.setText("4.0");
        panelRound1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 160, -1, -1));

        jLabel3.setFont(new java.awt.Font("Open Sans Medium", 0, 26)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(41, 204, 122));
        jLabel3.setText("Proyecto Transversal");
        panelRound1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(247, 110, -1, -1));

        jLabel4.setFont(new java.awt.Font("Open Sans Medium", 0, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Argentina");
        panelRound1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 150, -1, -1));

        jLabel5.setFont(new java.awt.Font("Open Sans Medium", 0, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Programa");
        panelRound1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(249, 190, -1, -1));

        text1.setForeground(new java.awt.Color(255, 184, 105));
        text1.setText("v 1.2.1 2023");
        panelRound1.add(text1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 370, 80, -1));

        getContentPane().add(panelRound1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 550, 410));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        if (realizado == false) {
            realizado = true;
            barra.setMaximum(49);
            barra.setMinimum(0);
            barra.setStringPainted(true);
            ejecutar.start();
        }
    }//GEN-LAST:event_formWindowActivated

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws UnsupportedLookAndFeelException {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PantallaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PantallaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PantallaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PantallaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PantallaInicio().setVisible(true);
            }
        });
        try {
            UIManager.setLookAndFeel(UIManager.getCrossPlatformLookAndFeelClassName());
        } catch (ClassNotFoundException ex) {
        } catch (InstantiationException ex) {
        } catch (IllegalAccessException ex) {
        } catch (UnsupportedLookAndFeelException ex) {
        }

        UIManager.put("ProgressBar.background", new Color(88, 101, 242, 0));//fondo de la barra por cargar
        UIManager.put("barra.foreground", new Color(255, 255, 255, 0));//color de las letras por cargar
        UIManager.put("ProgressBar.selectionBackground", new Color(255, 255, 255, 0));//fondo de la barra en progreso
        UIManager.put("ProgressBar.selectionForeground", new Color(255, 255, 255, 0));//color de las letras en progreso
    }

    private class hilo extends Thread {

        @Override
        public void run() {
            try {
                for (int i = 0; i < 51; i++) {
                    barra.setValue(i);
                    repaint();
                    switch (i) {
                        case 0:
                            text.setText("Pse-Int");
                            break;
                        case 13:
                            text.setText("Programando en java");
                            break;
                        case 30:
                            text.setText("Desarrolando App");
                            break;
                        case 50: {
                            text.setText("Carga finalizada");
                            VistaLogin objeto = new VistaLogin();
                            objeto.setVisible(true);
                            objeto.setLocationRelativeTo(PantallaInicio.this);
                            PantallaInicio.this.dispose();
                            break;
                        }

                    }
                    Thread.sleep(100);
                }

            } catch (InterruptedException ex) {
                Logger.getLogger(PantallaInicio.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JProgressBar barra;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private universidadejemplo.Vistas.PanelRound panelRound1;
    private javax.swing.JLabel text;
    private javax.swing.JLabel text1;
    // End of variables declaration//GEN-END:variables
}
