/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package universidadejemplo.Vistas;

import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListCellRenderer;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.SwingConstants;
import javax.swing.plaf.basic.BasicComboBoxUI;
import universidadejemplo.accesoADatos.*;
import universidadejemplo.Entidades.*;

/**
 *
 * @author USURIO
 */
public class VistaRecuperarPassword extends javax.swing.JFrame {

    private LoginData loginData;
    private boolean pregunta = true;

    /**
     * Creates new form VistaLogin
     */
    public VistaRecuperarPassword() {
        setUndecorated(true);
        initComponents();
        //Para que no se vea nada
        VistaRecuperarPassword.this.getRootPane().setOpaque(false);
        //Para darle color
        VistaRecuperarPassword.this.getContentPane().setBackground(new Color(0, 0, 0, 0));
        VistaRecuperarPassword.this.setBackground(new Color(0, 0, 0, 0));
        this.setResizable(false);
        this.setLocationRelativeTo(this);
        if (pregunta) {
            passwoe.setVisible(false);
            passwoe1.setVisible(false);
            jPasswordField1.setVisible(false);
            jPasswordField2.setVisible(false);
            jSeparator1.setVisible(false);
            jSeparator2.setVisible(false);
            jLabel1.setText("Ingresar");
        }
        if (jTxtUsuario.getText().isEmpty() || jTxtUsuario.getText().equalsIgnoreCase("Ingrese un Usuario")) {
            jTxtUsuario.setText("Ingrese un Usuario");
        }
        if (jTxtRespuesta.getText().isEmpty() || jTxtRespuesta.getText().equalsIgnoreCase("Conteste a la pregunta elegida")) {
            jTxtRespuesta.setText("Conteste a la pregunta elegida");
        }
        cargarCombo();
        darleFormaAlComboBox();
        panelRound2.requestFocus();

    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelRound2 = new universidadejemplo.Vistas.PanelRound();
        btnCrear = new universidadejemplo.Vistas.PanelRound();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        passwoe1 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        jSeparator1 = new javax.swing.JSeparator();
        passwoe = new javax.swing.JLabel();
        jPasswordField2 = new javax.swing.JPasswordField();
        jSeparator2 = new javax.swing.JSeparator();
        jTxtRespuesta = new javax.swing.JTextField();
        jSRespuesta = new javax.swing.JSeparator();
        jComboBox1 = new javax.swing.JComboBox<>();
        jTxtUsuario = new javax.swing.JTextField();
        jSUsuario = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelRound2.setBackground(new java.awt.Color(28, 27, 41));
        panelRound2.setRoundBottomLeft(50);
        panelRound2.setRoundBottomRight(50);
        panelRound2.setRoundTopLeft(50);
        panelRound2.setRoundTopRight(50);
        panelRound2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnCrear.setBackground(new java.awt.Color(88, 101, 242));
        btnCrear.setRoundBottomLeft(40);
        btnCrear.setRoundBottomRight(40);
        btnCrear.setRoundTopLeft(40);
        btnCrear.setRoundTopRight(40);
        btnCrear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCrearMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCrearMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCrearMouseExited(evt);
            }
        });
        btnCrear.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(88, 101, 242));
        jLabel1.setFont(new java.awt.Font("Open Sans SemiBold", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(228, 228, 231));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Crear");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCrear.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 340, 40));

        panelRound2.add(btnCrear, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 340, 40));

        jLabel5.setFont(new java.awt.Font("Open Sans Medium", 0, 22)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(228, 228, 231));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Nueva contraseña");
        panelRound2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 400, -1));

        jLabel4.setBackground(new java.awt.Color(228, 228, 231));
        jLabel4.setFont(new java.awt.Font("Open Sans Medium", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(228, 228, 231));
        jLabel4.setText("X");
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel4MouseExited(evt);
            }
        });
        panelRound2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 10, -1, -1));

        passwoe1.setFont(new java.awt.Font("Open Sans Medium", 0, 14)); // NOI18N
        passwoe1.setForeground(new java.awt.Color(228, 228, 231));
        passwoe1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        passwoe1.setText("Ingrese una contraseña");
        panelRound2.add(passwoe1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 400, -1));

        jPasswordField1.setBackground(new java.awt.Color(28, 27, 41));
        jPasswordField1.setFont(new java.awt.Font("Open Sans Medium", 0, 14)); // NOI18N
        jPasswordField1.setForeground(new java.awt.Color(228, 228, 231));
        jPasswordField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPasswordField1.setText("Ingrese su password");
        jPasswordField1.setBorder(null);
        jPasswordField1.setCaretColor(new java.awt.Color(228, 228, 231));
        jPasswordField1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jPasswordField1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jPasswordField1FocusLost(evt);
            }
        });
        jPasswordField1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPasswordField1MouseClicked(evt);
            }
        });
        panelRound2.add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 340, 30));

        jSeparator1.setBackground(new java.awt.Color(228, 228, 231));
        jSeparator1.setForeground(new java.awt.Color(228, 228, 231));
        panelRound2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 340, 10));

        passwoe.setFont(new java.awt.Font("Open Sans Medium", 0, 14)); // NOI18N
        passwoe.setForeground(new java.awt.Color(228, 228, 231));
        passwoe.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        passwoe.setText("Repita la contraseña");
        panelRound2.add(passwoe, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 400, -1));

        jPasswordField2.setBackground(new java.awt.Color(28, 27, 41));
        jPasswordField2.setFont(new java.awt.Font("Open Sans Medium", 0, 14)); // NOI18N
        jPasswordField2.setForeground(new java.awt.Color(228, 228, 231));
        jPasswordField2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPasswordField2.setText("Repita el password");
        jPasswordField2.setBorder(null);
        jPasswordField2.setCaretColor(new java.awt.Color(228, 228, 231));
        jPasswordField2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jPasswordField2FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jPasswordField2FocusLost(evt);
            }
        });
        jPasswordField2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPasswordField2MouseClicked(evt);
            }
        });
        panelRound2.add(jPasswordField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 340, 30));

        jSeparator2.setBackground(new java.awt.Color(228, 228, 231));
        jSeparator2.setForeground(new java.awt.Color(228, 228, 231));
        panelRound2.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 340, 10));

        jTxtRespuesta.setBackground(new java.awt.Color(28, 27, 41));
        jTxtRespuesta.setFont(new java.awt.Font("Open Sans Medium", 0, 14)); // NOI18N
        jTxtRespuesta.setForeground(new java.awt.Color(228, 228, 231));
        jTxtRespuesta.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTxtRespuesta.setBorder(null);
        jTxtRespuesta.setCaretColor(new java.awt.Color(228, 228, 231));
        jTxtRespuesta.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTxtRespuestaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTxtRespuestaFocusLost(evt);
            }
        });
        jTxtRespuesta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTxtRespuestaMouseClicked(evt);
            }
        });
        panelRound2.add(jTxtRespuesta, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 340, 30));

        jSRespuesta.setBackground(new java.awt.Color(228, 228, 231));
        jSRespuesta.setForeground(new java.awt.Color(228, 228, 231));
        panelRound2.add(jSRespuesta, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 340, 10));

        jComboBox1.setBackground(new java.awt.Color(28, 27, 41));
        jComboBox1.setFont(new java.awt.Font("Open Sans Medium", 0, 14)); // NOI18N
        jComboBox1.setForeground(new java.awt.Color(228, 228, 231));
        panelRound2.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 340, -1));

        jTxtUsuario.setBackground(new java.awt.Color(28, 27, 41));
        jTxtUsuario.setFont(new java.awt.Font("Open Sans Medium", 0, 14)); // NOI18N
        jTxtUsuario.setForeground(new java.awt.Color(228, 228, 231));
        jTxtUsuario.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTxtUsuario.setBorder(null);
        jTxtUsuario.setCaretColor(new java.awt.Color(228, 228, 231));
        jTxtUsuario.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTxtUsuarioFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTxtUsuarioFocusLost(evt);
            }
        });
        jTxtUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTxtUsuarioMouseClicked(evt);
            }
        });
        panelRound2.add(jTxtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 340, 30));

        jSUsuario.setBackground(new java.awt.Color(228, 228, 231));
        jSUsuario.setForeground(new java.awt.Color(228, 228, 231));
        panelRound2.add(jSUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 340, 10));

        getContentPane().add(panelRound2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 310));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCrearMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCrearMouseEntered
        btnCrear.setBackground(new Color(121, 131, 245));
    }//GEN-LAST:event_btnCrearMouseEntered

    private void btnCrearMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCrearMouseExited
        btnCrear.setBackground(new Color(88, 101, 242));
    }//GEN-LAST:event_btnCrearMouseExited

    private void btnCrearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCrearMouseClicked
         loginData = new LoginData();
        Login usuario = loginData.buscarLoginPorUsuario(jTxtUsuario.getText());
        if (pregunta) {
            loginData = new LoginData();

            try {
//                usuario = loginData.buscarLoginPorUsuario(jTxtUsuario.getText());
                
                if (jComboBox1.getItemAt(jComboBox1.getSelectedIndex()).equals(usuario.getPregunta()) && jTxtRespuesta.getText().equals(usuario.getRespueta())) {
                    pregunta = false;
                    passwoe.setVisible(true);
                    passwoe1.setVisible(true);
                    jPasswordField1.setVisible(true);
                    jPasswordField2.setVisible(true);
                    jSeparator1.setVisible(true);
                    jSeparator2.setVisible(true);
                    jLabel1.setText("Cambiar");
                    jTxtUsuario.setVisible(false);
                    jComboBox1.setVisible(false);
                    jTxtRespuesta.setVisible(false);
                    jSUsuario.setVisible(false);
                    jSRespuesta.setVisible(pregunta);
                }

            } catch (NullPointerException e) {
//                jLerror.setForeground(Color.red);
//                jLerror.setText("*Usuario y/o contraseña incorrecto");
//                jLerror.setVisible(true);
//                jSeparator1.setForeground(Color.red);
//                jSeparator1.setBackground(Color.red);
//                jSeparator2.setForeground(Color.red);
//                jSeparator2.setBackground(Color.red);

            } finally {
                panelRound2.requestFocus();
            }
        }else{
            if(String.valueOf(jPasswordField1.getPassword()).equalsIgnoreCase(String.valueOf(jPasswordField2.getPassword()))){
                usuario.setNombre(usuario.getNombre());
                usuario.setApellido(usuario.getApellido());
                usuario.setMail(usuario.getMail());
                usuario.setPregunta(usuario.getPregunta());
                usuario.setRespueta(usuario.getRespueta());
                usuario.setIdLogin(usuario.getIdLogin());
                usuario.setUsuario(usuario.getUsuario());
               usuario.setContrasenia(String.valueOf(jPasswordField1.getPassword()));
               loginData.modificarLogin(usuario);
            }
        }
    }//GEN-LAST:event_btnCrearMouseClicked

    private void jLabel4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseExited
        jLabel4.setForeground(new Color(228, 228, 231));
    }//GEN-LAST:event_jLabel4MouseExited

    private void jLabel4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseEntered
        jLabel4.setForeground(new Color(121, 131, 245));
    }//GEN-LAST:event_jLabel4MouseEntered

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jPasswordField1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPasswordField1FocusGained
        if (String.valueOf(jPasswordField1.getPassword()).equalsIgnoreCase("Ingrese su password")) {
            jPasswordField1.setText("");
        }
        //        if (incorrecto) {
        //            jLerror.setVisible(false);
        //            jSeparator1.setForeground(new Color(228, 228, 231));
        //            jSeparator1.setBackground(new Color(228, 228, 231));
        //        }
    }//GEN-LAST:event_jPasswordField1FocusGained

    private void jPasswordField1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPasswordField1FocusLost
        if (String.valueOf(jPasswordField1.getPassword()).isEmpty() || String.valueOf(jPasswordField1.getPassword()).equalsIgnoreCase("Ingrese su password")) {
            jPasswordField1.setText("Ingrese su password");
        }
    }//GEN-LAST:event_jPasswordField1FocusLost

    private void jPasswordField1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPasswordField1MouseClicked
        if (String.valueOf(jPasswordField1.getPassword()).equalsIgnoreCase("Ingrese su password")) {
            jPasswordField1.setText("");
        }
        passwoe1.setText("Ingrese una Contraseña");
        passwoe1.setForeground(new Color(228, 228, 231));
        jSeparator1.setForeground(new Color(228, 228, 231));
        jSeparator1.setBackground(new Color(228, 228, 231));
    }//GEN-LAST:event_jPasswordField1MouseClicked

    private void jPasswordField2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPasswordField2FocusGained
        if (String.valueOf(jPasswordField2.getPassword()).equalsIgnoreCase("Repita el password")) {
            jPasswordField2.setText("");
        }
    }//GEN-LAST:event_jPasswordField2FocusGained

    private void jPasswordField2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPasswordField2FocusLost
        if (String.valueOf(jPasswordField2.getPassword()).isEmpty() || String.valueOf(jPasswordField2.getPassword()).equalsIgnoreCase("Repita el password")) {
            jPasswordField2.setText("Repita el password");
        }
    }//GEN-LAST:event_jPasswordField2FocusLost

    private void jPasswordField2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPasswordField2MouseClicked
        if (String.valueOf(jPasswordField2.getPassword()).equalsIgnoreCase("Repita el password")) {
            jPasswordField2.setText("");
        }
        passwoe.setText("Repita el Contraseña");
        passwoe.setForeground(new Color(228, 228, 231));
        jSeparator2.setForeground(new Color(228, 228, 231));
        jSeparator2.setBackground(new Color(228, 228, 231));
    }//GEN-LAST:event_jPasswordField2MouseClicked

    private void jTxtRespuestaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTxtRespuestaFocusGained
        if (jTxtRespuesta.getText().equalsIgnoreCase("Conteste a la pregunta elegida")) {
            jTxtRespuesta.setText("");
        }
    }//GEN-LAST:event_jTxtRespuestaFocusGained

    private void jTxtRespuestaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTxtRespuestaFocusLost
        if (jTxtRespuesta.getText().isEmpty() || jTxtRespuesta.getText().equalsIgnoreCase("Conteste a la pregunta elegida")) {
            jTxtRespuesta.setText("Conteste a la pregunta elegida");
        }
    }//GEN-LAST:event_jTxtRespuestaFocusLost

    private void jTxtRespuestaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTxtRespuestaMouseClicked
        if (jTxtRespuesta.getText().equalsIgnoreCase("Conteste a la pregunta elegida")) {
            jTxtRespuesta.setText("");
        }
        jSRespuesta.setForeground(new Color(228, 228, 231));
        jSRespuesta.setBackground(new Color(228, 228, 231));
    }//GEN-LAST:event_jTxtRespuestaMouseClicked

    private void jTxtUsuarioFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTxtUsuarioFocusGained
        if (jTxtUsuario.getText().equalsIgnoreCase("Ingrese un Usuario")) {
            jTxtUsuario.setText("");
        }
    }//GEN-LAST:event_jTxtUsuarioFocusGained

    private void jTxtUsuarioFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTxtUsuarioFocusLost
        if (jTxtUsuario.getText().isEmpty() || jTxtUsuario.getText().equalsIgnoreCase("Ingrese un Usuario")) {
            jTxtUsuario.setText("Ingrese un Usuario");
        }
    }//GEN-LAST:event_jTxtUsuarioFocusLost

    private void jTxtUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTxtUsuarioMouseClicked
        if (jTxtUsuario.getText().equalsIgnoreCase("Ingrese un Usuario")) {
            jTxtUsuario.setText("");
        }
        jSUsuario.setForeground(new Color(228, 228, 231));
        jSUsuario.setBackground(new Color(228, 228, 231));
    }//GEN-LAST:event_jTxtUsuarioMouseClicked

    private void darleFormaAlComboBox() {
        jComboBox1.setUI(new BasicComboBoxUI() {
            private boolean isPopupVisible = false;
            private boolean isImageChanged = false;

            @Override
            protected JButton createArrowButton() {
                JButton arrowButton = new JButton(new ImageIcon("src/img/Recurso 2.png"));

                arrowButton.setBorderPainted(false);
                arrowButton.setContentAreaFilled(false);
                arrowButton.setFocusPainted(false);
                arrowButton.setOpaque(false);

                arrowButton.addActionListener(new ActionListener() {
                    @Override
                    public void actionPerformed(ActionEvent e) {
                        if (!isPopupVisible) {
                            isImageChanged = !isImageChanged;
                            if (isImageChanged) {
                                arrowButton.setIcon(new ImageIcon("src/img/Recurso 3.png"));
                            } else {
                                arrowButton.setIcon(new ImageIcon("src/img/Recurso 2.png"));
                            }
                        }
                    }
                });
                jComboBox1.addMouseListener(new MouseListener() {
                    @Override
                    public void mouseClicked(MouseEvent e) {
                        if (!isPopupVisible) {
                            isImageChanged = !isImageChanged;
                            if (isImageChanged) {
                                arrowButton.setIcon(new ImageIcon("src/img/Recurso 3.png"));
                            } else {
                                arrowButton.setIcon(new ImageIcon("src/img/Recurso 2.png"));
                            }
                        }
                    }

                    @Override
                    public void mousePressed(MouseEvent e) {
                    }

                    @Override
                    public void mouseReleased(MouseEvent e) {
                    }

                    @Override
                    public void mouseEntered(MouseEvent e) {
                    }

                    @Override
                    public void mouseExited(MouseEvent e) {
                    }

                });

                jComboBox1.addActionListener(new ActionListener() {
                    @Override
                    public void actionPerformed(ActionEvent e) {
                        if (!isPopupVisible) {
                            isImageChanged = !isImageChanged;
                            if (isImageChanged) {
                                arrowButton.setIcon(new ImageIcon("src/img/Recurso 3.png"));
                            } else {
                                arrowButton.setIcon(new ImageIcon("src/img/Recurso 2.png"));
                            }
                        }
                    }

                });

                return arrowButton;
            }

        });

        jComboBox1.setForeground(new Color(228, 228, 231));
        jComboBox1.setFocusable(false);
        DefaultListCellRenderer renderer = new DefaultListCellRenderer();
        renderer.setHorizontalAlignment(SwingConstants.CENTER);
    }

    public List<String> preguntas() {
        List<String> prefuntas = new ArrayList<>();

        prefuntas.add("¿Como se llamaba tu primer pareja?");
        prefuntas.add("¿Como se llamaba tu primer mascota?");
        prefuntas.add("¿Cual es tu lugar favorito?");
        prefuntas.add("¿Cual es tu juego favorito?");

        return prefuntas;
    }

    public void cargarCombo() {
        DefaultComboBoxModel<String> mdlCombo = new DefaultComboBoxModel(preguntas().toArray());
        jComboBox1.setModel(mdlCombo);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private universidadejemplo.Vistas.PanelRound btnCrear;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JPasswordField jPasswordField2;
    private javax.swing.JSeparator jSRespuesta;
    private javax.swing.JSeparator jSUsuario;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField jTxtRespuesta;
    private javax.swing.JTextField jTxtUsuario;
    private universidadejemplo.Vistas.PanelRound panelRound2;
    private javax.swing.JLabel passwoe;
    private javax.swing.JLabel passwoe1;
    // End of variables declaration//GEN-END:variables
}
