/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package universidadejemplo.Vistas;

import java.awt.Color;
import java.awt.HeadlessException;
import javax.swing.JOptionPane;
import universidadejemplo.Entidades.*;
import universidadejemplo.accesoADatos.*;

/**
 *
 * @author USURIO
 */
public class vistaMateria extends javax.swing.JInternalFrame {
    
    private MateriaData materia;
    
    public vistaMateria() {
        initComponents();
        setOpaque(false);
        setClosable(true);
        
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator2 = new javax.swing.JSeparator();
        panelRound1 = new universidadejemplo.Vistas.PanelRound();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        panelRound2 = new universidadejemplo.Vistas.PanelRound();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTxNombreMateria = new javax.swing.JTextField();
        jBBuscar = new javax.swing.JButton();
        jTxCodigo = new javax.swing.JTextField();
        jTxAnio = new javax.swing.JTextField();
        btnAgregar = new universidadejemplo.Vistas.PanelRound();
        jLabel8 = new javax.swing.JLabel();
        btnEliminar = new universidadejemplo.Vistas.PanelRound();
        jLabel9 = new javax.swing.JLabel();
        btnGuardar = new universidadejemplo.Vistas.PanelRound();
        jLabel10 = new javax.swing.JLabel();
        btnSalir = new universidadejemplo.Vistas.PanelRound();
        jLabel11 = new javax.swing.JLabel();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelRound1.setBackground(new java.awt.Color(41, 40, 65));
        panelRound1.setRoundTopLeft(50);
        panelRound1.setRoundTopRight(50);
        panelRound1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Materia");
        jLabel2.setAlignmentX(50.0F);
        jLabel2.setAlignmentY(50.0F);
        panelRound1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 25, 462, -1));

        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));
        panelRound1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(53, 63, 365, 16));

        getContentPane().add(panelRound1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 460, 80));

        panelRound2.setBackground(new java.awt.Color(28, 27, 41));
        panelRound2.setRoundBottomLeft(50);
        panelRound2.setRoundBottomRight(50);
        panelRound2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Codigo");
        panelRound2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 104, -1));

        jLabel4.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Nombre");
        panelRound2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 94, -1));

        jLabel5.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Año");
        panelRound2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 94, -1));

        jTxNombreMateria.setBackground(new java.awt.Color(28, 27, 41));
        jTxNombreMateria.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jTxNombreMateria.setForeground(new java.awt.Color(228, 228, 231));
        panelRound2.add(jTxNombreMateria, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 90, 324, -1));

        jBBuscar.setBackground(new java.awt.Color(28, 27, 41));
        jBBuscar.setFont(new java.awt.Font("Open Sans Medium", 0, 18)); // NOI18N
        jBBuscar.setForeground(new java.awt.Color(228, 228, 231));
        jBBuscar.setText("Buscar");
        jBBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBBuscarActionPerformed(evt);
            }
        });
        panelRound2.add(jBBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 30, 96, -1));

        jTxCodigo.setBackground(new java.awt.Color(28, 27, 41));
        jTxCodigo.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jTxCodigo.setForeground(new java.awt.Color(228, 228, 231));
        panelRound2.add(jTxCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, 165, -1));

        jTxAnio.setBackground(new java.awt.Color(28, 27, 41));
        jTxAnio.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jTxAnio.setForeground(new java.awt.Color(228, 228, 231));
        panelRound2.add(jTxAnio, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 150, 199, -1));

        btnAgregar.setBackground(new java.awt.Color(88, 101, 242));
        btnAgregar.setRoundBottomLeft(40);
        btnAgregar.setRoundBottomRight(40);
        btnAgregar.setRoundTopLeft(40);
        btnAgregar.setRoundTopRight(40);
        btnAgregar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAgregarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAgregarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAgregarMouseExited(evt);
            }
        });
        btnAgregar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setBackground(new java.awt.Color(88, 101, 242));
        jLabel8.setFont(new java.awt.Font("Open Sans SemiBold", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(228, 228, 231));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Agregar");
        jLabel8.setAlignmentX(40.0F);
        jLabel8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAgregar.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 100, 40));

        panelRound2.add(btnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 100, 40));

        btnEliminar.setBackground(new java.awt.Color(88, 101, 242));
        btnEliminar.setRoundBottomLeft(40);
        btnEliminar.setRoundBottomRight(40);
        btnEliminar.setRoundTopLeft(40);
        btnEliminar.setRoundTopRight(40);
        btnEliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEliminarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnEliminarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnEliminarMouseExited(evt);
            }
        });
        btnEliminar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setBackground(new java.awt.Color(88, 101, 242));
        jLabel9.setFont(new java.awt.Font("Open Sans SemiBold", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(228, 228, 231));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Eliminar");
        jLabel9.setAlignmentX(40.0F);
        jLabel9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEliminar.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 100, 40));

        panelRound2.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 220, 100, 40));

        btnGuardar.setBackground(new java.awt.Color(88, 101, 242));
        btnGuardar.setRoundBottomLeft(40);
        btnGuardar.setRoundBottomRight(40);
        btnGuardar.setRoundTopLeft(40);
        btnGuardar.setRoundTopRight(40);
        btnGuardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnGuardarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnGuardarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnGuardarMouseExited(evt);
            }
        });
        btnGuardar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setBackground(new java.awt.Color(88, 101, 242));
        jLabel10.setFont(new java.awt.Font("Open Sans SemiBold", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(228, 228, 231));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Guardar");
        jLabel10.setAlignmentX(40.0F);
        jLabel10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGuardar.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 100, 40));

        panelRound2.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 220, 100, 40));

        btnSalir.setBackground(new java.awt.Color(88, 101, 242));
        btnSalir.setRoundBottomLeft(40);
        btnSalir.setRoundBottomRight(40);
        btnSalir.setRoundTopLeft(40);
        btnSalir.setRoundTopRight(40);
        btnSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSalirMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSalirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSalirMouseExited(evt);
            }
        });
        btnSalir.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setBackground(new java.awt.Color(88, 101, 242));
        jLabel11.setFont(new java.awt.Font("Open Sans SemiBold", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(228, 228, 231));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Salir");
        jLabel11.setAlignmentX(40.0F);
        jLabel11.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSalir.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 80, 40));

        panelRound2.add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 220, 100, 40));

        getContentPane().add(panelRound2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 460, 290));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBBuscarActionPerformed
        materia = new MateriaData();
        if (jTxCodigo.getText().isEmpty() && jTxNombreMateria.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Por favor ingrese un codigo o materia");
        } else if(!jTxCodigo.getText().isEmpty()) {
            try {
                Materia mate = materia.buscarMateria(Integer.parseInt(jTxCodigo.getText()));
                jTxNombreMateria.setText(mate.getNombre());
                jTxAnio.setText(String.valueOf(mate.getAnio()));
//                jRadioEstadoMateria.setSelected(mate.isActivo());
            } catch (NullPointerException e) {
//                JOptionPane.showMessageDialog(null, "La materia ingresado no existe o es incorrecto el codigo");
            }
        }
//        else if(!jTxNombreMateria.getText().isEmpty()) {
//            try {
//                Materia mate = materia.buscarMateria(Integer.parseInt(jTxCodigo.getText()));
//                jTxNombreMateria.setText(mate.getNombre());
//                jTxAnio.setText(String.valueOf(mate.getAnio()));
////                jRadioEstadoMateria.setSelected(mate.isActivo());
//            } catch (NullPointerException e) {
//                JOptionPane.showMessageDialog(null, "La materia ingresado no existe o es incorrecto el codigo");
//            }
//        }
    }//GEN-LAST:event_jBBuscarActionPerformed

    private void btnAgregarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAgregarMouseClicked
        materia = new MateriaData();
        if (jTxNombreMateria.getText().isEmpty() || jTxAnio.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "revise que los campos no este vacios");
        } else if(!jTxCodigo.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Por favor deje el codigo vacio");
        }else{
            try {
                Materia mate = new Materia(jTxNombreMateria.getText(), Integer.parseInt(jTxAnio.getText()), true);
                materia.guardarMateria(mate);
                jTxCodigo.setText(String.valueOf(mate.getIdMateria()));
            } catch (HeadlessException | NumberFormatException e) {
                
//                JOptionPane.showMessageDialog(null, "Error al cargar el materia" + e.getMessage());
            }
        }
    }//GEN-LAST:event_btnAgregarMouseClicked

    private void btnAgregarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAgregarMouseEntered
        btnAgregar.setBackground(new Color(121, 131, 245));
    }//GEN-LAST:event_btnAgregarMouseEntered

    private void btnAgregarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAgregarMouseExited
        btnAgregar.setBackground(new Color(88, 101, 242));
    }//GEN-LAST:event_btnAgregarMouseExited

    private void btnEliminarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarMouseClicked
        materia = new MateriaData();
        if (jTxCodigo.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Por favor ingrese el codigo de la materia correcto");
        } else {
            try {
                materia.eliminarMateria(Integer.parseInt(jTxCodigo.getText()));
            } catch (NullPointerException e) {
//                JOptionPane.showMessageDialog(null, "La materia ingresada no existe o es incorrecta");
            }
        }
    }//GEN-LAST:event_btnEliminarMouseClicked

    private void btnEliminarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarMouseEntered
        btnEliminar.setBackground(new Color(121, 131, 245));// TODO add your handling code here:
    }//GEN-LAST:event_btnEliminarMouseEntered

    private void btnEliminarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarMouseExited
       btnEliminar.setBackground(new Color(88, 101, 242));
    }//GEN-LAST:event_btnEliminarMouseExited

    private void btnGuardarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGuardarMouseClicked
         materia = new MateriaData();
        if (jTxCodigo.getText().isEmpty() || jTxNombreMateria.getText().isEmpty() || jTxAnio.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "revise que los campos no este vacios");
        } else {
            try {
                Materia mate = materia.buscarMateria(Integer.parseInt(jTxCodigo.getText()));
                mate.setIdMateria(Integer.parseInt(jTxCodigo.getText()));
                mate.setNombre(jTxNombreMateria.getText());
                mate.setAnio(Integer.parseInt(jTxAnio.getText()));
//                mate.setActivo(jRadioEstadoMateria.isSelected());
                String si = "SI";
                String no = "NO";
                String cancelar = "Cancelar";
                Object[] opciones = {si, no};
                int confirmacion = JOptionPane.showOptionDialog(this, "¿Desea modificar los datos de la materia?", "", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null, opciones, si);
                System.out.println(confirmacion);
                if (confirmacion == 0) {
                    materia.modificarMateria(mate);
                }
            } catch (HeadlessException | NumberFormatException e) {
                
//                JOptionPane.showMessageDialog(null, "Error al cargar la materia " + e.getMessage());
            }
        }
    }//GEN-LAST:event_btnGuardarMouseClicked

    private void btnGuardarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGuardarMouseEntered
        btnGuardar.setBackground(new Color(121, 131, 245));
    }//GEN-LAST:event_btnGuardarMouseEntered

    private void btnGuardarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGuardarMouseExited
        btnGuardar.setBackground(new Color(88, 101, 242));
    }//GEN-LAST:event_btnGuardarMouseExited

    private void btnSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalirMouseClicked
        this.dispose();
    }//GEN-LAST:event_btnSalirMouseClicked

    private void btnSalirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalirMouseEntered
       btnSalir.setBackground(new Color(121, 131, 245));
    }//GEN-LAST:event_btnSalirMouseEntered

    private void btnSalirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalirMouseExited
       btnSalir.setBackground(new Color(88, 101, 242));
    }//GEN-LAST:event_btnSalirMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private universidadejemplo.Vistas.PanelRound btnAgregar;
    private universidadejemplo.Vistas.PanelRound btnEliminar;
    private universidadejemplo.Vistas.PanelRound btnGuardar;
    private universidadejemplo.Vistas.PanelRound btnSalir;
    private javax.swing.JButton jBBuscar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField jTxAnio;
    private javax.swing.JTextField jTxCodigo;
    private javax.swing.JTextField jTxNombreMateria;
    private universidadejemplo.Vistas.PanelRound panelRound1;
    private universidadejemplo.Vistas.PanelRound panelRound2;
    // End of variables declaration//GEN-END:variables
}
