/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package universidadejemplo.Vistas;

import java.awt.Color;
import universidadejemplo.accesoADatos.*;
import universidadejemplo.Entidades.*;

/**
 *
 * @author USURIO
 */
public class VistaLogin extends javax.swing.JFrame {

    private LoginData loginData;

    /**
     * Creates new form VistaLogin
     */
    public VistaLogin() {
        setUndecorated(true);
        initComponents();
        //Para que no se vea nada
        VistaLogin.this.getRootPane().setOpaque(false);
        //Para darle color
        VistaLogin.this.getContentPane().setBackground(new Color(0, 0, 0, 0));
        VistaLogin.this.setBackground(new Color(0, 0, 0, 0));
        this.setResizable(false);
        this.setLocationRelativeTo(this);
        panelRound2.requestFocus();
        if (jTxtUsuario.getText().isEmpty() || jTxtUsuario.getText().equalsIgnoreCase("Ingrese su usuario")) {
            jTxtUsuario.setText("Ingrese su usuario");
        }
        jLerror.setVisible(false);

    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelRound1 = new universidadejemplo.Vistas.PanelRound();
        panelRound2 = new universidadejemplo.Vistas.PanelRound();
        jPasswordField1 = new javax.swing.JPasswordField();
        jTxtUsuario = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        btnCrear = new universidadejemplo.Vistas.PanelRound();
        jLabel1 = new javax.swing.JLabel();
        btnIngresar = new universidadejemplo.Vistas.PanelRound();
        jLabel3 = new javax.swing.JLabel();
        jLerror = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jlOlvidaste = new javax.swing.JLabel();
        panelRound3 = new universidadejemplo.Vistas.PanelRound();
        panelRound4 = new universidadejemplo.Vistas.PanelRound();
        panelRound5 = new universidadejemplo.Vistas.PanelRound();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelRound1.setBackground(new java.awt.Color(41, 40, 65));
        panelRound1.setRoundBottomLeft(50);
        panelRound1.setRoundBottomRight(50);
        panelRound1.setRoundTopLeft(50);
        panelRound1.setRoundTopRight(50);
        panelRound1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelRound2.setBackground(new java.awt.Color(28, 27, 41));
        panelRound2.setRoundBottomLeft(50);
        panelRound2.setRoundBottomRight(50);
        panelRound2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPasswordField1.setBackground(new java.awt.Color(28, 27, 41));
        jPasswordField1.setFont(new java.awt.Font("Open Sans Medium", 0, 14)); // NOI18N
        jPasswordField1.setForeground(new java.awt.Color(228, 228, 231));
        jPasswordField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPasswordField1.setText("Ingrese su password");
        jPasswordField1.setBorder(null);
        jPasswordField1.setCaretColor(new java.awt.Color(228, 228, 231));
        jPasswordField1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jPasswordField1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jPasswordField1FocusLost(evt);
            }
        });
        jPasswordField1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPasswordField1MouseClicked(evt);
            }
        });
        panelRound2.add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 320, 30));

        jTxtUsuario.setBackground(new java.awt.Color(28, 27, 41));
        jTxtUsuario.setFont(new java.awt.Font("Open Sans Medium", 0, 14)); // NOI18N
        jTxtUsuario.setForeground(new java.awt.Color(228, 228, 231));
        jTxtUsuario.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTxtUsuario.setBorder(null);
        jTxtUsuario.setCaretColor(new java.awt.Color(228, 228, 231));
        jTxtUsuario.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTxtUsuarioFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTxtUsuarioFocusLost(evt);
            }
        });
        jTxtUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTxtUsuarioMouseClicked(evt);
            }
        });
        panelRound2.add(jTxtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 320, 30));

        jSeparator1.setBackground(new java.awt.Color(228, 228, 231));
        jSeparator1.setForeground(new java.awt.Color(228, 228, 231));
        panelRound2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 320, 10));

        jSeparator2.setBackground(new java.awt.Color(228, 228, 231));
        jSeparator2.setForeground(new java.awt.Color(228, 228, 231));
        panelRound2.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 320, 10));

        btnCrear.setBackground(new java.awt.Color(88, 101, 242));
        btnCrear.setRoundBottomLeft(40);
        btnCrear.setRoundBottomRight(40);
        btnCrear.setRoundTopLeft(40);
        btnCrear.setRoundTopRight(40);
        btnCrear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCrearMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCrearMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCrearMouseExited(evt);
            }
        });
        btnCrear.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(88, 101, 242));
        jLabel1.setFont(new java.awt.Font("Open Sans SemiBold", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(228, 228, 231));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Crear");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCrear.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 1, 150, 40));

        panelRound2.add(btnCrear, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, 150, 40));

        btnIngresar.setBackground(new java.awt.Color(88, 101, 242));
        btnIngresar.setRoundBottomLeft(40);
        btnIngresar.setRoundBottomRight(40);
        btnIngresar.setRoundTopLeft(40);
        btnIngresar.setRoundTopRight(40);
        btnIngresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnIngresarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnIngresarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnIngresarMouseExited(evt);
            }
        });
        btnIngresar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Open Sans SemiBold", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(228, 228, 231));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Ingresar");
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnIngresar.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 1, 150, 40));

        panelRound2.add(btnIngresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 240, 150, -1));

        jLerror.setFont(new java.awt.Font("Open Sans Medium", 0, 14)); // NOI18N
        jLerror.setForeground(new java.awt.Color(228, 228, 231));
        jLerror.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLerror.setText("Inicio de sesion");
        panelRound2.add(jLerror, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 400, -1));

        jLabel5.setFont(new java.awt.Font("Open Sans Medium", 0, 22)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(228, 228, 231));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Inicio de sesion");
        panelRound2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 20, 400, -1));

        jlOlvidaste.setFont(new java.awt.Font("Open Sans Medium", 0, 12)); // NOI18N
        jlOlvidaste.setForeground(new java.awt.Color(228, 228, 231));
        jlOlvidaste.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlOlvidaste.setText("¿olvidaste la contraseña?");
        jlOlvidaste.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jlOlvidaste.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlOlvidasteMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jlOlvidasteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jlOlvidasteMouseExited(evt);
            }
        });
        panelRound2.add(jlOlvidaste, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 400, -1));

        panelRound1.add(panelRound2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 400, 310));

        panelRound3.setBackground(new java.awt.Color(255, 184, 105));
        panelRound3.setRoundBottomLeft(125);
        panelRound3.setRoundBottomRight(125);
        panelRound3.setRoundTopLeft(125);
        panelRound3.setRoundTopRight(125);
        panelRound3.setVerifyInputWhenFocusTarget(false);
        panelRound3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelRound4.setBackground(new java.awt.Color(255, 156, 105));
        panelRound4.setRoundBottomLeft(50);
        panelRound4.setRoundBottomRight(50);
        panelRound4.setRoundTopLeft(50);
        panelRound4.setRoundTopRight(50);
        panelRound4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        panelRound3.add(panelRound4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 50, 50));

        panelRound5.setBackground(new java.awt.Color(255, 156, 105));
        panelRound5.setRoundBottomLeft(255);
        panelRound5.setRoundBottomRight(255);
        panelRound5.setRoundTopLeft(100);
        panelRound5.setRoundTopRight(100);

        javax.swing.GroupLayout panelRound5Layout = new javax.swing.GroupLayout(panelRound5);
        panelRound5.setLayout(panelRound5Layout);
        panelRound5Layout.setHorizontalGroup(
            panelRound5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 110, Short.MAX_VALUE)
        );
        panelRound5Layout.setVerticalGroup(
            panelRound5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        panelRound3.add(panelRound5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 110, 60));
        panelRound5.getAccessibleContext().setAccessibleDescription("");

        panelRound1.add(panelRound3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 30, 130, 130));

        jLabel4.setBackground(new java.awt.Color(228, 228, 231));
        jLabel4.setFont(new java.awt.Font("Open Sans Medium", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(228, 228, 231));
        jLabel4.setText("X");
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel4MouseExited(evt);
            }
        });
        panelRound1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 10, -1, -1));

        getContentPane().add(panelRound1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTxtUsuarioFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTxtUsuarioFocusLost
        if (jTxtUsuario.getText().isEmpty() || jTxtUsuario.getText().equalsIgnoreCase("Ingrese su usuario")) {
            jTxtUsuario.setText("Ingrese su usuario");
        }
    }//GEN-LAST:event_jTxtUsuarioFocusLost

    private void jTxtUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTxtUsuarioMouseClicked
        if (jTxtUsuario.getText().equalsIgnoreCase("Ingrese su usuario")) {
            jTxtUsuario.setText("");
        }

        jLerror.setVisible(false);
        jSeparator2.setForeground(new Color(228, 228, 231));
        jSeparator2.setBackground(new Color(228, 228, 231));


    }//GEN-LAST:event_jTxtUsuarioMouseClicked

    private void jTxtUsuarioFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTxtUsuarioFocusGained
        if (jTxtUsuario.getText().equalsIgnoreCase("Ingrese su usuario")) {
            jTxtUsuario.setText("");
        }
//        if (incorrecto) {
//            jLerror.setVisible(false);
//            jSeparator2.setForeground(new Color(228, 228, 231));
//            jSeparator2.setBackground(new Color(228, 228, 231));
//        }
    }//GEN-LAST:event_jTxtUsuarioFocusGained

    private void jPasswordField1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPasswordField1FocusLost
        if (String.valueOf(jPasswordField1.getPassword()).isEmpty() || String.valueOf(jPasswordField1.getPassword()).equalsIgnoreCase("Ingrese su password")) {
            jPasswordField1.setText("Ingrese su password");
        }

    }//GEN-LAST:event_jPasswordField1FocusLost

    private void jPasswordField1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPasswordField1MouseClicked
        if (String.valueOf(jPasswordField1.getPassword()).equalsIgnoreCase("Ingrese su password")) {
            jPasswordField1.setText("");
        }

        jLerror.setVisible(false);
        jSeparator1.setForeground(new Color(228, 228, 231));
        jSeparator1.setBackground(new Color(228, 228, 231));

    }//GEN-LAST:event_jPasswordField1MouseClicked

    private void jPasswordField1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPasswordField1FocusGained
        if (String.valueOf(jPasswordField1.getPassword()).equalsIgnoreCase("Ingrese su password")) {
            jPasswordField1.setText("");
        }
//        if (incorrecto) {
//            jLerror.setVisible(false);
//            jSeparator1.setForeground(new Color(228, 228, 231));
//            jSeparator1.setBackground(new Color(228, 228, 231));
//        }
    }//GEN-LAST:event_jPasswordField1FocusGained

    private void btnIngresarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnIngresarMouseEntered
        btnIngresar.setBackground(new Color(121, 131, 245));
    }//GEN-LAST:event_btnIngresarMouseEntered

    private void btnIngresarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnIngresarMouseExited
        btnIngresar.setBackground(new Color(88, 101, 242));
    }//GEN-LAST:event_btnIngresarMouseExited

    private void btnCrearMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCrearMouseEntered
        btnCrear.setBackground(new Color(121, 131, 245));
    }//GEN-LAST:event_btnCrearMouseEntered

    private void btnCrearMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCrearMouseExited
        btnCrear.setBackground(new Color(88, 101, 242));
    }//GEN-LAST:event_btnCrearMouseExited

    private void btnIngresarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnIngresarMouseClicked
        loginData = new LoginData();

        try {
            Login usuario = loginData.buscarLoginPorUsuario(jTxtUsuario.getText());
            if (jTxtUsuario.getText().equals(usuario.getUsuario()) && String.valueOf(jPasswordField1.getPassword()).equals(usuario.getContrasenia())) {
                MenuPrincipal menu = new MenuPrincipal();
                menu.setVisible(true);
                this.setVisible(false);
            }
//            if (jTxtUsuario.getText().isEmpty()) {
//                jLerror.setForeground(Color.red);
//                jLerror.setText("*ingrese un usuario ");
//                jLerror.setVisible(true);
//                jSeparator2.setForeground(Color.red);
//                jSeparator2.setBackground(Color.red);
//
//            } else if (String.valueOf(jPasswordField1.getPassword()).isEmpty()) {
//                jLerror.setForeground(Color.red);
//                jLerror.setText("*ingrese una contraseña ");
//                jLerror.setVisible(true);
//                jSeparator1.setForeground(Color.red);
//                jSeparator1.setBackground(Color.red);
//            }

        } catch (NullPointerException e) {
            jLerror.setForeground(Color.red);
            jLerror.setText("*Usuario y/o contraseña incorrecto");
            jLerror.setVisible(true);
            jSeparator1.setForeground(Color.red);
            jSeparator1.setBackground(Color.red);
            jSeparator2.setForeground(Color.red);
            jSeparator2.setBackground(Color.red);

        } finally {
            panelRound2.requestFocus();
        }

    }//GEN-LAST:event_btnIngresarMouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jLabel4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseEntered
        jLabel4.setForeground(new Color(121, 131, 245));    }//GEN-LAST:event_jLabel4MouseEntered

    private void jLabel4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseExited
        jLabel4.setForeground(new Color(228, 228, 231));
    }//GEN-LAST:event_jLabel4MouseExited

    private void btnCrearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCrearMouseClicked
        VistaCrearLogin vista = new VistaCrearLogin();
        vista.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnCrearMouseClicked

    private void jlOlvidasteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlOlvidasteMouseEntered
        jlOlvidaste.setForeground(new Color(255,184,105));
    }//GEN-LAST:event_jlOlvidasteMouseEntered

    private void jlOlvidasteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlOlvidasteMouseExited
        
        jlOlvidaste.setForeground(new Color(228,228,231));
    }//GEN-LAST:event_jlOlvidasteMouseExited

    private void jlOlvidasteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlOlvidasteMouseClicked
        VistaRecuperarPassword contrasena = new VistaRecuperarPassword();
        contrasena.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jlOlvidasteMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private universidadejemplo.Vistas.PanelRound btnCrear;
    private universidadejemplo.Vistas.PanelRound btnIngresar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLerror;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField jTxtUsuario;
    private javax.swing.JLabel jlOlvidaste;
    private universidadejemplo.Vistas.PanelRound panelRound1;
    private universidadejemplo.Vistas.PanelRound panelRound2;
    private universidadejemplo.Vistas.PanelRound panelRound3;
    private universidadejemplo.Vistas.PanelRound panelRound4;
    private universidadejemplo.Vistas.PanelRound panelRound5;
    // End of variables declaration//GEN-END:variables
}
